if (NOT DEFINED DECODER OR NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "AAC decode validation requires DECODER, INPUT and OUTPUT")
endif()
execute_process(COMMAND "${DECODER}" -hide_banner -loglevel error -y -i "${INPUT}" -f f32le "${OUTPUT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
if (NOT result EQUAL 0)
    message(FATAL_ERROR "AAC decoder failed (${result}): ${stderr}")
endif()
file(SIZE "${OUTPUT}" decoded_bytes)
if (decoded_bytes LESS 8192)
    message(FATAL_ERROR "AAC decoder returned insufficient audio")
endif()
file(READ "${OUTPUT}" decoded HEX)
string(REGEX REPLACE "0" "" nonzero "${decoded}")
if (NOT nonzero STREQUAL "")
    message(FATAL_ERROR "Decoded holding AAC contains nonzero PCM samples")
endif()
message(STATUS "Real holding AAC decoded: ${decoded_bytes} bytes; every float PCM sample is zero")